networks:
  primeira-network:
    name: primeira-network
    external: true
    driver: bridge

services:
  mysql:
    networks:
      - primeira-network
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root

  api-rocket:
    container_name: api-rocket
    networks:
      - primeira-network
    build:
      context: .
    ports:
      - 3001:3000
    depends_on:
      - mysql
